steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/scenic-impact-450921-a1/jaswant-100995271/image:${COMMIT_SHA}', '.']

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/scenic-impact-450921-a1/jaswant-100995271/image:${COMMIT_SHA}']

  
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
